
name: Dependent Jobs Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 for main
        uses: actions/checkout@v4

      - name: setup java version
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: build test
        run: ant

      - name: build complete
        run: echo "Build finished."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: running tests
        run: echo "Running tests"

      - name: tests complete
        run: echo "Tests finished."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploying
        run: echo "Deploying..."

      - name: deployment complete
        run: echo "Deployment finished."