name: Multi-Platform Workflow

on:
  push:
    branches:
      - master

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 ubuntu
        uses: actions/checkout@v4

      - name: OS info
        run: uname -a

      - name: message
        run: echo "Hello from Ubuntu"

      - name: displaying file
        run: |
          echo "This file was created on Ubuntu." > ubuntu.txt
          cat ubuntu.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - name: step 1 windows
        uses: actions/checkout@v4

      - name: OS info
        run: systeminfo

      - name: message
        run: echo Hello from Windows

      - name: displaying file
        run: |
          echo This file was created on Windows > windows.txt
          type windows.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - name: step 1 mac
        uses: actions/checkout@v4

      - name: OS info
        run: uname -a

      - name: message
        run: echo "Hello from macOS"

      - name: displaying file
        run: |
          echo "This file was created on macOS." > macos.txt
          cat macos.txt