name: Multi-Platform Workflow

on:
  push:
    branches:
      - master

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: step 1 for ubuntu - OS info
        run: uname -a
      - name: Create File and Display
        run: |
          echo "Hello from Ubuntu" > ubuntu.txt
          cat ubuntu.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: step 1 for windows - OS info
        run: systeminfo
      - name: Create File and Display
        run: |
          echo Hello from Windows > windows.txt
          type windows.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: step 1 for mac OS - OS info
        run: uname -a
      - name: Create File and Display
        run: |
          echo "Hello from macOS" > macos.txt
          cat macos.txt